 const PAGEKEYS={
    HOME:"HOME",
    GOALS:"GOALS",
    SINGIN:"SINGIN",
    MAIN:"MAIN",
    HABITS:"HABITS",
    TASKS:"TASKS",
    HABIT_TRACKING:"HABIT_TRACKING",
    HABIT_CALENDAR:"HABIT_CALENDAR",

}
export default PAGEKEYS;