 const PAGEKEYS={
    HOME:"HOME",
    GOALS:"GOALS",
    SINGIN:"SINGIN",
    MAIN:"MAIN",
    HABITS:"HABITS",
    TASKS:"TASKS",
    HABIT_TRACKING:"HABIT_TRACKING",
    HABIT_CALENDAR:"HABIT_CALENDAR",
    TASK_CALENDAR:"TASK_CALENDAR",
    GOAL_STATS:"GOAL_STATS",
    TASK_STATS:"TASK_STATS",
    HABIT_STATS:"HABIT_STATS",

}

export default PAGEKEYS;