import PAGEKEYS from "./pageKeys";
const ROUTES = {};
ROUTES[PAGEKEYS["MAIN"]] = "/main";
ROUTES[PAGEKEYS["SIGNIN"]] = "/signin";
ROUTES[PAGEKEYS["HOME"]] = "/main/home";
ROUTES[PAGEKEYS["GOALS"]] = "/main/goals";
ROUTES[PAGEKEYS["HABITS"]] = "/main/habits";
ROUTES[PAGEKEYS["TASKS"]] = "/main/tasks";
ROUTES[PAGEKEYS["HABIT_TRACKING"]] = "/main/habit-tracking";
ROUTES[PAGEKEYS["HABIT_CALENDAR"]] = "/main/habit-calendar";
ROUTES[PAGEKEYS["TASK_CALENDAR"]] = "/main/task-calendar";
export default ROUTES;
